### ISSUE TITLE
Make tree traversal from events easier

### ISSUE THREAD

**Issue by memeplex** [acrisci/i3ipc-python#100]
Currently when you get an event with a container, this container is not connected to the tree (descendents and parent are empty). This is understandable since the event payload doesn't include this information. But could you provide a more convenient interface? Maybe a way to quickly locate the container in the tree returned by get_tree.

**Comment by acrisci** [comment]
Yeah I would support this feature.

**Comment by acrisci** [comment]
Actually what about this?

```python3
def handler(i3, e):
    con = i3.get_tree().find_by_id(e.container.id)
```

**Comment by memeplex** [comment]
Looks good to me!

**Comment by acrisci** [comment]
Ok cool.
