### ISSUE TITLE
Make example program that can go to nth window in particular workspace

### ISSUE THREAD

**Issue by o-jasper** [acrisci/i3ipc-python#102]
Something like `nth_window_in_workspace.py $workspace $window_index`, clamp the index; <0 it goes to the first, >=len(windows) go to last.

I want add `mode "window_map" {..}` and have each column of my keyboard map to a window. Should try do it myself.. Note: [examples/focus-next-visible.py](/acrisci/i3ipc-python/blob/master/examples/focus-next-visible.py) might be helpful as to how to do it.

**Comment by acrisci** [comment]
Yeah I would accept that. Let me know if you need any guidance.

**Comment by o-jasper** [comment]
[Here it is](https://github.com/o-jasper/i3ipc-python/blob/nth_window_in_workspace/examples/nth_window_in_workspace.py), but maybe still has bugs. Also it will basically need a line for every button mapped `~/.config/i3/config` maybe should have some suggested parts of that file in here?

**Comment by o-jasper** [comment]
Like have `examples/config/nth_window_in_workspace.config` or `examples/nth_window_in_workspace/` and then `nth_window_in_workspace.py` and `config` in there?
