### ISSUE TITLE
Container doesn't contain 'visible' attribute 

### ISSUE THREAD

**Issue by jcalbert** [acrisci/i3ipc-python#108]
The Container `__init__` uses a list of attributes, `ipc_properties`, that should include `'visible'` but does not.

https://github.com/acrisci/i3ipc-python/blob/d446c6cbe7283ece50a37f9d72ee9b670fc389b1/i3ipc/i3ipc.py#L925-L927

https://github.com/acrisci/i3ipc-python/blob/d446c6cbe7283ece50a37f9d72ee9b670fc389b1/i3ipc/i3ipc.py#L995-L1000

**Comment by acrisci** [comment]
Oh ok put it in there then.

**Comment by jcalbert** [comment]
Looking closer, it seems that only `get_workspaces()` actually returns a visibility info.

[This](https://github.com/jcalbert/i3ipc-python/commit/cf87f762cb083584e9b61a80d57904e29c87e6ae) uses that function to fill in the relevant data, but it's hackish.  Another option would be to just drop `visible` from the attribute docstring.

**Comment by acrisci** [comment]
> This uses that function to fill in the relevant data,

That won't work because the window can be hidden in a stack or by a floating window.

> Another option would be to just drop visible from the attribute docstring.

Yeah that's probably best.

**Comment by acrisci** [comment]
Search the i3 tracker for this. I think it's already been discussed. You'll have to fix this in i3 for me to support it.

**Comment by sainathadapa** [comment]
@acrisci I looked for issues related to this on `i3` repo, but couldn't find an issue that deals with exactly the current use case. Do you know if there is a way to filter for the list of containers which are 'visible' in a workspace?

**Comment by acrisci** [comment]
You have to write it.

**Comment by sainathadapa** [comment]
Understood, but I'm unable to infer that information in case of `tabbed` containers from the output of `i3-msg -t get_tree`. All the children of `tabbed` containers exist in the `focus`, and not just the visible one. Any ideas?

**Comment by acrisci** [comment]
The first one in the list is on top.

**Comment by jcalbert** [comment]
@sainathadapa 
get_tree doesn't have the ability to tell which containers are visible.  You can have a look at my workaround here: [here](https://github.com/jcalbert/dotfiles/blob/i3/i3/ckb-colors.py)

https://github.com/jcalbert/dotfiles/blob/b107a829235c2aa045c6885eeb0fb93a61f8424b/i3/ckb-colors.py#L30-L44

Basically, it uses `get_workspaces` to infer what containers are visible, active, etc.  I don't think I've tested it with tabbed containers, though, so ymmv.

**Comment by sainathadapa** [comment]
interesting, i'll try using both of your suggestions @acrisci @jcalbert and see if it works.
