### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Synthetica9** [acrisci/i3ipc-python#109]
I'd like to get the PID of a window, but no released version has the commit that introduced that feature (bd0224e55e34fca9608d468daf2a0513b20c9951). Is there a timeline for the next release?

**Comment by acrisci** [comment]
I'm definitely due for a release. Just need to sort out #105 then I'll get it out there soon.

**Comment by acrisci** [comment]
https://github.com/acrisci/i3ipc-python/releases/tag/v1.7.1
