### ISSUE TITLE
Make parameters mandatory for example

### ISSUE THREAD

**Issue by teto** [acrisci/i3ipc-python#11]
I don' believe this script does anything without --workspace and --command so making the arguments mandatory would help the user understand what's going on:
https://github.com/acrisci/i3ipc-python/blob/master/examples/app-on-ws-init.py

**Comment by acrisci** [comment]
Yeah, some of the examples need a cleanup. They should all have a help string and some documentation.

Help would be appreciated in cleaning these up a bit. Feel free to submit a PR.

**Comment by acrisci** [comment]
Fixed in #13.
