### ISSUE TITLE
script request/ help wanted

### ISSUE THREAD

**Issue by sharethewisdom** [acrisci/i3ipc-python#14]
I would like to launch a terminal window for each of the workspaces 1 trough 8 when they're initiated. 

In stead of using eight instances of `app-on-ws-init.py`, I would like to have one script running that compares the initiated WS's name with a list of names (or with an expression). There's no need for argument parsing.

help is greatly appreciated!

**Comment by acrisci** [comment]
You can just make the argument for workspaces accept a list.

**Comment by acrisci** [comment]
Example:

    app-on-ws-init.py --workspace 3 5 --command 'notify-send ok'

**Comment by sharethewisdom** [comment]
thanks!
