### ISSUE TITLE
i3ipc-python does not compile in Python 3.4 with 'KeyError: '_convert''

### ISSUE THREAD

**Issue by pronobis** [acrisci/i3ipc-python#15]
When installing i3ipc using PIP in Python 3.4 (ubuntu 15.10), the following error occurs:

```
Downloading/unpacking enum34 (from i3ipc)
  Downloading enum34-1.0.4.tar.gz
  Running setup.py (path:/tmp/pip-build-00v68qq2/enum34/setup.py) egg_info for package enum34
    Traceback (most recent call last):
      File "/tmp/pip-build-00v68qq2/enum34/enum/__init__.py", line 371, in __getattr__
        return cls._member_map_[name]
    KeyError: '_convert'
```

Since there doesn't seem to be need for enum34 in Python 3.4. It should be ok to just remove it from the dependencies then.

**Comment by acrisci** [comment]
enum34 is still required for python2.

I can't reproduce this on my machine. It looks like an issue with enum34.

**Comment by pronobis** [comment]
It is exactly the same issue as reported here https://github.com/opentok/Opentok-Python-SDK/pull/70 and here https://github.com/jstasiak/python-zeroconf/pull/22 . And this commit https://github.com/brisad/python-zeroconf/commit/ad0f94a946e48d99a329aa326dd11220219d4026 shows how to include enum34 only for python < 3.4. Could you please introduce that in i3ipc?

**Comment by acrisci** [comment]
It's not going to be as simple as this because last time I checked, setup.py does not actually run at the time of install, but the time of packaging. I haven't gotten around to learning how to package for multiple versions of python yet.

**Comment by pronobis** [comment]
There is a simpler solution. Instead of using enum34, one should use enum-compat (https://pypi.python.org/pypi/enum-compat/) as a dependency. The sole purpose of that package is exactly to be a noop on Python 3.4+.

As far as I know enum34 is not meant to be used for Python 3.4+ and therefore might cause problems.

**Comment by acrisci** [comment]
I think the better solution is just to write it out.

Lesson learned: you can't do a python library without writing in the intersection of python2/python3.

**Comment by astronouth7303** [comment]
+1 `enum-compat`. Python is batteries included, don't go rewriting stuff.

Also, can you fix this and push a release? I was hoping to get a bug fix on other issues.

**Comment by acrisci** [comment]
Yes, sorry for neglecting this project. I am working on it today.

**Comment by acrisci** [comment]
Thanks for the suggestion to use `enum-compat`. I will work on doing a release for this today.

**Comment by pronobis** [comment]
Great. Thanks!

**Comment by pronobis** [comment]
Did you manage to make the release? Pip does not seem to be aware of the changes yet.

**Comment by acrisci** [comment]
There are only two hard problems in computer science: writing documentation and releasing.

**Comment by bussyjd** [comment]
Please release

**Comment by acrisci** [comment]
I did a release.

**Comment by pronobis** [comment]
Works great. Thanks!
