### ISSUE TITLE
container.mark is None even if the container has marks

### ISSUE THREAD

**Issue by infokiller** [acrisci/i3ipc-python#20]
To reproduce, simply mark any container and then check the mark attribute of the python object for that container.

**Comment by acrisci** [comment]
What is your i3 version? Use `i3 --version`.

**Comment by infokiller** [comment]
`i3 version 4.8-850-gcaeb193 (2015-12-03, branch "bug-2090")`

**Comment by acrisci** [comment]
It works on 4.11

**Comment by acrisci** [comment]
I just tested it on release 4.8 and it works fine.

Try `i3ipc.Connection().get_tree().find_marked("foo").mark`

**Comment by infokiller** [comment]
Just tested it in 4.11 and it indeed works. I built the 4.8 manually to get some bugfix from another branch- I'm not sure if that's related.
I think we can close the issue for now and reopen it if I'll reproduce it on a new release.

Thanks a lot for your quick responses!
