### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by MCManuelLP** [acrisci/i3ipc-python#38]
I have some code that is run every second:

	focused = i3ipc.Connection().get_tree().find_focused()
	# I use this to get some information about the current window
After a few hours of running it, it started to really use a lot of memory so I investigated it with [objgraph](http://mg.pov.lt/objgraph/) and `objgraph.show_growth()` showed that this is what's left over after running the code snippet:

	dict        5700        +6
	tuple       4330        +6
	weakref     2033        +3
	type        1201        +3
So I don't know if there is any way to get rid of these unused objects as they seriously tax the memory after a while...

**Comment by acrisci** [comment]
Can you provide a simple script that reproduces the issue with instructions to reproduce the memory leak?

**Comment by astronouth7303** [comment]
How does objgraph relate to the GC cycle? Are these actual live objects, or could they be unreferenced but uncollected?

**Comment by MCManuelLP** [comment]
import i3ipc
	import objgraph
	objgraph.show_growth() #initial growth from import statements and such
	while True:

		value = i3ipc.Connection().get_tree().get_focused()
		del value

**Comment by acrisci** [comment]
When I run that code, the objgraph does not grow. The call to `show_graph()` does not print anything.

**Comment by astronouth7303** [comment]
I'm getting continuous output under Python 3.5.1.

Running `gc.collect()` afterwards shows no cleanup.

**Comment by MCManuelLP** [comment]
So, I've tested this again in python 2.7.11, 3.4.3 and 3.5.1 with i3ipc version 1.2.0, could it be that this is fixed on master?

**Comment by MCManuelLP** [comment]
Yeah, tested this again, seems to be fixed on master, sorry that I didn't check that...

**Comment by acrisci** [comment]
@astronouth7303 can you test on master and confirm?

**Comment by astronouth7303** [comment]
Fixed for me. No output and memory usage is rock steady.
