### ISSUE TITLE
 as I get the scripts to run ?

### ISSUE THREAD

**Issue by elhackerlibre** [acrisci/i3ipc-python#39]
Hi...
Excuse my asking
as I get the scripts to run ?
I searched if you have a manual but do not see it !
It saddens me to do this kind of questions ...
I hope I can get out of doubt

**Comment by acrisci** [comment]
Hi,

Look at the example in the README.md for an example of how to write a script. There are also a lot of example you can look at [here](https://github.com/acrisci/i3ipc-python/tree/master/examples) of scripts people have written.

Run the script like you would a normal python script. From the command line, use `python ./script.py` where `./script.py` is your script name.

There is no other documentation right now, but I will write it soon.

If you have a specific question let me know.
