### ISSUE TITLE
struct.pack('I',msg_length).decode('utf-8') will fail

### ISSUE THREAD

**Issue by JHeiner** [acrisci/i3ipc-python#4]
For example, the bytes marked in red at http://en.wikipedia.org/wiki/UTF-8#Codepage_layout cannot be decoded. There are also restrictions on which bytes are allowed to appear before/after others. If you're interested all the rules are explained fairly well there on wikipedia.

The + operator concats bytes, so Connection._pack() can simply:
```python
  pb = payload.encode()
  return b'i3-ipc' + struct.pack('=II',len(pb),msg_type) + pb
```

**Comment by acrisci** [comment]
This seems reasonable. I will make this change.
