### ISSUE TITLE
Move focused container

### ISSUE THREAD

**Issue by 1dollarsteak** [acrisci/i3ipc-python#40]
Hello,

http://pastebin.com/XFPDdfRk

When running I get two same values for x. When I rerun this they differ from the last run. Is this behaviour API related?

**Comment by acrisci** [comment]
Yeah, if the container moves, then the rect will change. Rect represents screen coordinates. The x value is the x value on the screen (horizontal position). When the container moves left, you should expect x to shrink (or stay the same).
