### ISSUE TITLE
can't subscribe to ipc-shutdown event

### ISSUE THREAD

**Issue by chrsclmn** [acrisci/i3ipc-python#42]
The command-on-exit example no longer works due to a bug that was introduced by commit 849858607ecd4ad45aa3caf2b1a983129f3ca182. Attempting to subscribe to "ipc-shutdown" triggers an exception:

```
$ python command-on-exit.py 
Traceback (most recent call last):
  File "command-on-exit.py", line 18, in <module>
    i3.on('ipc-shutdown', on_shutdown)
  File "/home/chrsclmn/git/i3ipc-python/i3ipc.py", line 332, in on
    raise Exception('event not implemented')
Exception: event not implemented
```
Since commit 849858607ecd4ad45aa3caf2b1a983129f3ca182, dashes in event names are replaced with underscores, which means `event == 'ipc-shutdown'` will always be false:

```python
    def on(self, detailed_event, handler):
        event = detailed_event.replace('-', '_')

        if detailed_event.count('::') > 0:
            [event, __] = detailed_event.split('::')

        # special case: ipc-shutdown is not in the protocol
        if event == 'ipc-shutdown':
            self._pubsub.subscribe(event, handler)
            return
```

**Comment by acrisci** [comment]
:+1:

**Comment by chrsclmn** [comment]
96a3da4 fixes the exception, but the handler doesn't get called because the event is still emitted with the old name. Pull request #43 fixes that and also updates the example.
