### ISSUE TITLE
Cannot get the correct workspace's layout

### ISSUE THREAD

**Issue by amosbird** [acrisci/i3ipc-python#45]
```
#!/usr/bin/env python3
import i3ipc
i3 = i3ipc.Connection()
ws = i3.get_tree().find_focused().workspace()
print(ws.layout)
```

This script will print `splith` no matter what the layout is.

**Comment by acrisci** [comment]
Hi,

FIrst of all, what version of i3 are you running? Run `i3 --version` and tell me the output.

Next, is this a problem with the library or the ipc itself? Try `i3-msg -t get_tree` and see if it is reporting a different layout on the workspace container than what the library is giving you.

**Comment by amosbird** [comment]
I was wrong about the layout property. It belongs to a container.
```
!/usr/bin/env python3
import i3ipc

i3 = i3ipc.Connection()
ws = i3.get_tree().find_focused().workspace()
layout = ws.descendents()[0].layout
if layout == 'tabbed':
    i3.command('layout default')
else:
    i3.command('layout tabbed')
```
This works fine. Thanks for the neat library.
