### ISSUE TITLE
find_marked and mark do not work

### ISSUE THREAD

**Issue by joepvd** [acrisci/i3ipc-python#47]
`find_marked` and `Con.mark` seem broken:

```
% ipython3
Python 3.5.2 (default, Jul  5 2016, 12:43:10) 

In [1]: import i3ipc

In [2]: i3ipc.Connection().get_tree().find_focused().command('mark m')

# See `[m]` appear in window decoration

In [3]: i3ipc.Connection().get_tree().find_marked('m')
Out[3]: []

In [4]: i3ipc.Connection().get_tree().find_focused().mark

In [5]: 
Do you really want to exit ([y]/n)? y

% pip3 freeze | grep ipc
i3ipc==1.2.0

% i3 --version
i3 version 4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors

% lsb_release -dcs
Ubuntu 16.04.1 LTS
xenial
```

**Comment by acrisci** [comment]
It's fixed in the development version.

I'm just now realizing how long it's been since a release. I'll get on that soon.

**Comment by joepvd** [comment]
Thanks!

Silly question. How would I install the development version? I've been multiple stabs, but consider the attempt failed at the moment. Maybe would be a good addition to `README.md`?

**Comment by joepvd** [comment]
That was easy :) Just copied `i3ipc.py` over to `~/.local/lib/python3.5/site-packages`, and overwrote the file from the distribution. Not pretty but it works :)

**Comment by acrisci** [comment]
Sorry, the project is kind of broken right now. I have a work project that is kind of kicking my butt but I think I will have time to fix it soon and do a release.

**Comment by joepvd** [comment]
Thanks for all the work you _are_ putting into this, @acrisci! This is a very useful and usable library. I use it hundreds of times every day :)
