### ISSUE TITLE
Catching exceptions raised by event handlers

### ISSUE THREAD

**Issue by minus7** [acrisci/i3ipc-python#52]
Not an issue but rather a design question: Should the main loop intercept exceptions raised by event handlers and swallow them, or, as it is now with i3ipc-python, just don't do anything about them and let them break the main loop?

Intercepting them makes the program more robust in cases of failure, letting them break the main loop makes it easier to discover problems (if the exceptions are not handled appropriately).
Does changing that, or providing a switch or a possibility to hook into them, make sense?

**Comment by acrisci** [comment]
Hi, sorry for not noticing this sooner. I don't get notified directly on repository issues.

I agree this can be a bit cumbersome and I have run into issues with this in my own scripts so I am open to adding something to make the interface nicer. What in particular would you suggest?

**Comment by minus7** [comment]
After discussing it, the only sensible thing to do is to let uncaught exceptions break the main loop since otherwise the program continues in an undefined state. It may also make sense to wrap the original exception so that its origin is clear; that's the only change I'd do. If the user really wants to swallow exceptions, they can do so in the handler code.
The main problem there is with just letting it break the main loop is that it won't terminate the program in case the main loop runs in an extra thread, like it has been the case for me. There doesn't seem to be a nice solution to that (as [`sys.exit()` in a thread doesn't terminate the program](http://stackoverflow.com/a/905224)). I poll `thread.is_alive()` from the main thread now and exit accordingly.

**Comment by acrisci** [comment]
I'm rewriting the connection to use asyncio in a separate package and I'm going to have this behavior. Exceptions in handler code will break the main loop.
