### ISSUE TITLE
'restart' command raises error because of missing ipc socket answer

### ISSUE THREAD

**Issue by grubersjoe** [acrisci/i3ipc-python#55]
When executing the `restart` command through the `i3.command` methode the following JSONDecodeError is raised, because the ipc socket doesn't return an answer. The command itself is executed correctly.

```python
>>> import i3ipc
>>> i3 = i3ipc.Connection()
>>> i3.command('restart')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joe/git/_vendor/i3ipc-python/i3ipc/i3ipc.py", line 418, in command
    return json.loads(data, object_hook=CommandReply)
  File "/usr/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0
```
I guess this happens, because the socket breaks down in the following method, after the command has been sent:

```python
def _ipc_send(self, sock, message_type, payload):
    sock.sendall(self._pack(message_type, payload))
    data, msg_type = self._ipc_recv(sock)
    return data
```

I'd send a PR, but I'm not quire sure how this should be fixed best.

**Comment by joepvd** [comment]
Related: https://github.com/acrisci/i3ipc-python/pull/25

**Comment by grubersjoe** [comment]
Thank you for pointing me to this issue. I just realized after reading acrisci's answer, that a `reload` is actually all I need. A `restart` isn't even required.

This issue can be closed, I think.
