### ISSUE TITLE
Please support Python2

### ISSUE THREAD

**Issue by FedericoCeratto** [acrisci/i3ipc-python#6]
Hello @acrisci and thank you for developing this library.
Would you consider supporting py2 as well.
It would be useful on systems where python3-xlib is not available yet, or where py2 is the default interpreter.

**Comment by acrisci** [comment]
Yeah, python2 support would be good.

**Comment by FedericoCeratto** [comment]
In the short term I'm using https://github.com/FedericoCeratto/i3-py

**Comment by acrisci** [comment]
I just pushed some changes that should make the library compatible with python 2. You will need the python [enum backport](https://pypi.python.org/pypi/enum34/) for it to work. 

@FedericoCeratto please test this and then I will close.

**Comment by FedericoCeratto** [comment]
@acrisci: thank you, it works and I sent you a pull request #7 - any plan to make a new release?

**Comment by acrisci** [comment]
Yeah, I'm gonna let it sit for a few days and then do a release for python2. I would also like to try to get some documentation in that release.

**Comment by acrisci** [comment]
@FedericoCeratto, I just did a release for both python versions here: https://pypi.python.org/pypi/i3ipc

Make sure that works ok for you.

**Comment by FedericoCeratto** [comment]
Thank you @acrisci - the library seems to be working ok on Python2!
The tar.gz on PyPI does not contain the examples directory, is that expected?
Also, would you mind tagging the releases on GitHub as well (the source tarballs from GH are slightly better)

**Comment by acrisci** [comment]
@FedericoCeratto, ok thanks for testing. I hope all the dependencies are right.

As for the examples, those are not released with the library. I wish we could figure out a way to do a proper "plugin system" for i3, but we would need to find a better way to distribute the scripts.

**Comment by FedericoCeratto** [comment]
@acrisci: the GitHub source tarball contains the examples and with it I was able to build .deb packages that install the examples as well.
