### ISSUE TITLE
Is it possible to unsubscribe from events?

### ISSUE THREAD

**Issue by francispotter** [acrisci/i3ipc-python#60]
Is it possible to unsubscribe from events? How?

**Comment by acrisci** [comment]
There is currently no way to unsubscribe from events but maybe we can put it in the library.

What is your use case?

**Comment by francispotter** [comment]
I'm trying to write code that launches specific applications in specific containers. It appears the only way to do that is to wait for the application window to open (by listening for the window::new event) and then move on to the next workspace/container. But once the window is open, I no longer need to listen for that event. It's not a problem from my end; I can quit out of the loop. But I wonder if i3 has a list of listeners somewhere in memory that should be cleaned up.

**Comment by acrisci** [comment]
There is no way to cleanly unsubscribe from the i3 ipc events themselves so the best I could do for you is to make your handler no longer notify. If you want that, you would have to make an issue with the i3 project.

This means the library would still receive and process any event for the `window` event but no notifiers would be triggered.

If you want to clean up the connection to the ipc, destroy the `Connection` instance itself.

**Comment by francispotter** [comment]
That's helpful, thanks.
