### ISSUE TITLE
get_tree, leaves, floating problem?

### ISSUE THREAD

**Issue by cyrinux** [acrisci/i3ipc-python#75]
Hi!
Please could you please look this issue https://github.com/maximbaz/dotfiles/issues/4
It is related a python scripts which use our lib, and a behaviour change between 2 versions.
Do you have an idea about the problem?
Regards,

**Comment by acrisci** [comment]
Yeah looks like a library issue. I will look into it tomorrow.

**Comment by cyrinux** [comment]
Ok thanks @acrisci !
ping @maximbaz

**Comment by acrisci** [comment]
I think this is fixed in #70 which was fairly recent.

**Comment by acrisci** [comment]
I just released 1.4.0 which I think should fix it.

**Comment by cyrinux** [comment]
Hi @acrisci , sorry the issue seems to be still here.
What can I do for help?

**Comment by maximbaz** [comment]
The problem is that `.leaves()` of `i3.get_tree().workspaces()` doesn't include floating windows, but `.leaves()` of `.i3.get_tree()` does. This example shows the difference, `iterate_tree` correctly discovers floating windows, but `iterate_workspaces` does not.

```python
#!/usr/bin/env python3

import i3ipc


def iterate_workspaces(i3):
    print('iterating workspaces')
    for _, workspace in enumerate(i3.get_tree().workspaces()):
        print('workspace name: ' + workspace.name)
        for leaf in workspace.leaves():
            print(leaf.name)
        print('------')
    print('iterating workspaces: DONE')


def iterate_tree(i3):
    print('iterating tree')
    root = i3.get_tree()
    print('root name: ' + root.name)
    for leaf in root.leaves():
        print(leaf.name)
    print('iterating tree: DONE')


def main():
    i3 = i3ipc.Connection()

    iterate_workspaces(i3)
    print('\n============\n')
    iterate_tree(i3)


if __name__ == '__main__':
    main()
```

**Comment by acrisci** [comment]
Can you try again with 54c9218? I think that fixes it. I added a test you can look at so we won't have regressions.

**Comment by maximbaz** [comment]
I confirm that the fix is working, thanks! 👍

**Comment by cyrinux** [comment]
Cool! Thanks it works!
