### ISSUE TITLE
i3 scratchpad toggle

### ISSUE THREAD

**Issue by EvilMegaDroid** [acrisci/i3ipc-python#79]
Do you think its possible to write a python script for having i3 scratchpad loop through apps insteed of hide and show. I'm trying to do it right now with this library but no luck so far. Is it i3 ipc limitation?

So far I'm getting the number of apps in scratchpad and if there are more than 1, execute 3 times conn.command("scratchpad show") but it doesn't work when I try to bind it.

Thanks

**Comment by acrisci** [comment]
Can you post some code I can look at?

**Comment by EvilMegaDroid** [comment]
Well to tell the truth I don't know if its a i3 upgrade but most of conn property do not work if I call scratchpad()
The script I was using was kind of faulty but so far I can't get my other ideas working since I can only get the number of open apps in scratchpad via this code.
```
import i3ipc
conn = i3ipc.Connection()
tree = conn_get_tree()
scratchpad = tree.scratchpad().focus # This gives us a list of id from the open app. I tried descendents but I get a empty list from that. Maybe an update broke it.

if len (scratchpad) > 1:
   conn.command("scratchpad show")
   conn.command("scratchpad show")
   conn.command("scratchpad show")
else:
   conn.command("scratchpad show")
```

I was testing this out before but it doesn't work given the fact that I can't know if the scratchpad is open since 3 times calling "scratchpad show" would hide it. A way i though was to use the visible property but that doesn't work since I can't get a list of containers. The descendents property gives me a empty list.

**Comment by acrisci** [comment]
There was a bug that might lead to scratchpad not giving the descendents, but I think it is fixed in the latest git version. Try that.

**Comment by EvilMegaDroid** [comment]
Your right, it seems that with latest github version the descendents works. Going to try and see if I can get the script working now :)

**Comment by EvilMegaDroid** [comment]
I finished the script now it works perfectly. It gets the id from ipc. Uses that get title via xprop and puts both title and id into a nested list which gets piped through rofi, rofi outputs an array number to slice the list and I run that through the ipc.command() and that way I can switch scratchpad windows fast.

**Comment by acrisci** [comment]
Cool I'll release soon :+1:
