### ISSUE TITLE
Subscription socket not closed properly

### ISSUE THREAD

**Issue by orestisf1993** [acrisci/i3ipc-python#83]
Related to https://github.com/i3/i3/issues/2999.

Minimal example:
```python
#!/usr/bin/env python3
import i3ipc


def on_ws_focus(self, e):
    print(e.old.name, '->', e.current.name)


for i in range(10):
    try:
        i3 = i3ipc.Connection()
        i3.on('workspace::focus', on_ws_focus)
        i3.main()
    except KeyboardInterrupt:
        print('ctrl-c pressed for connection #', i)
        # uncomment to unbug: i3.main_quit()
```

With the line commented out: https://bpaste.net/raw/abbf7e3ea890
With the line uncommented: https://bpaste.net/raw/667fe94a2d58

This will lead i3 to get stuck receiving EAGAIN errors while trying to write to the socket fd because the client is not reading from the pipe:
https://github.com/i3/i3/blob/55dd5b8d8406c45b8ba406eabe453bc8596c1336/libi3/safewrappers.c#L75-L79

**Comment by orestisf1993** [comment]
Hmm, I guess users are expected to call `main_quit()`?

Maybe we can add support for context managers using contextlib? Then users can use
```python
with i3ipc.Connection() as i3:
...
```
instead.

**Comment by acrisci** [comment]
> Maybe we can add support for context managers using contextlib?

It's a good idea, but I don't want to break the interface by making it required. We should think of a solution for the way people use the library now. Maybe I can just add a finally block somewhere.

**Comment by orestisf1993** [comment]
> It's a good idea, but I don't want to break the interface by making it required.

Yes, it should work like that:

```python
#!/usr/bin/env python3
for i in range(10):
    try:
        with i3ipc.Connection() as i3:
            i3.on('workspace::focus', on_ws_focus)
            i3.main()
    except KeyboardInterrupt:
        print('ctrl-c pressed for connection #', i)
```

but the old code should work too.

> Maybe I can just add a finally block somewhere.

Can happen, if you prefer that no-one should depend on the subscription socket being left open after `main()` exits. ie, this is a bug and not a feature.

**Comment by acrisci** [comment]
Yeah, that's how I think `main()` should work. I think this handles most of the use cases for the library nicely.

The socket setup/teardown functions are meant to be public to support other use cases like integration with other main loops and stuff like that. If you can provide a concrete use case that is not covered nicely, please open another issue and we can discuss the contextlib approach more.

**Comment by orestisf1993** [comment]
The only other case would be people that use the setup function but forget to remember to use the teardown function. Also, maybe closing the cmd_socket?
