### ISSUE TITLE
Exception: Failed to retrieve the i3 IPC socket path

### ISSUE THREAD

**Issue by Pikaro** [acrisci/i3ipc-python#91]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/i3ipc/i3ipc.py", line 341, in __init__
    close_fds=True, universal_newlines=True).strip()
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['i3', '--get-socketpath']' died with <Signals.SIGUSR1: 10>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.i3expo/i3expod.py", line 511, in <module>
    update_state(i3, None)
  File "/home/user/.i3expo/i3expod.py", line 218, in update_state
    if current_workspace.num == i3ipc.Connection().get_tree().find_focused().workspace().num:
  File "/usr/local/lib/python3.6/dist-packages/i3ipc/i3ipc.py", line 343, in __init__
    raise Exception('Failed to retrieve the i3 IPC socket path')
Exception: Failed to retrieve the i3 IPC socket path
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
```

This occurs apparently randomly whenever the above line (`i3ipc.Connection().get_tree().find_focused().workspace().num`) is executed. Unfortunately it's rare enough that I can't easily narrow down the circumstances, but there appears to be no simple reason. Called in a while True, this does exactly what it's supposed to do for hours at least, suspends included. 

Please advise what additional information would be necessary. Installed from pip3, current version 1.5.1.

Edit: Oh, and nvm the SIGUSR1 thing - the function gets executed only when I send that signal.

**Comment by acrisci** [comment]
This looks like a problem within the i3 binary.

**Comment by acrisci** [comment]
This will help: https://github.com/i3/i3/issues/3476

**Comment by acrisci** [comment]
The new asyncio connection will use [python-xlib](https://github.com/python-xlib/python-xlib) to get the socketpath from the root window in preference over the binary which should fix this even more.
