### ISSUE TITLE
i3ipc removes a window object that is still referenced in code

### ISSUE THREAD

**Issue by Hi-Angel** [acrisci/i3ipc-python#94]
# Steps to reproduce

1. save the following script as `inactive-window-transparency.py`:
	```python
	import i3ipc

	ipc = i3ipc.Connection()
	prev_focused = None

	for window in ipc.get_tree():
		if window.focused:
			prev_focused = window
		else:
			window.command('opacity 0.8')

	if (prev_focused == None):
		raise Exception('No focused window found!')

	def on_window_focus(ipc, focused):
		focused.container.command('opacity 1')
		prev_focused.command('opacity 0.8')
		prev_focused = focused.container

	ipc.on("window::focus", on_window_focus)
	ipc.main() # enter command loop
	```
2. Execute `python inactive-window-transparency.py`
3. Unfocus a window *(e.g. switch a workspace)*

# Expected

In i3 nothing, in sway the inactive window would become transparent

# Actual

The script quits with:

```
Traceback (most recent call last):
  File "inactive-window-transparency.py", line 21, in <module>
    ipc.main() # enter command loop
  File "/usr/lib/python3.7/site-packages/i3ipc/i3ipc.py", line 728, in main
    while not self.event_socket_poll():
  File "/usr/lib/python3.7/site-packages/i3ipc/i3ipc.py", line 716, in event_socket_poll
    self._pubsub.emit(event_name, event)
  File "/usr/lib/python3.7/site-packages/i3ipc/i3ipc.py", line 311, in emit
    s['handler'](self.conn, data)
  File "inactive-window-transparency.py", line 17, in on_window_focus
    prev_focused.command('opacity 0.8')
UnboundLocalError: local variable 'prev_focused' referenced before assignment
```
# Additional info

Tested on both i3 and sway.
i3ipc version: 1.6.0

**Comment by orestisf1993** [comment]
https://docs.python.org/3/faq/programming.html#what-are-the-rules-for-local-and-global-variables-in-python
> In Python, variables that are only referenced inside a function are implicitly global. If a variable is assigned a value anywhere within the function’s body, it’s assumed to be a local unless explicitly declared as global.

You need to use `global prev_focused` inside `on_window_focus`

**Comment by Hi-Angel** [comment]
Oh, thanks! Sorry for the noise, though I probably wouldn't have figured that nuance out without spending some hours staring at i3ipc.py :)
