### ISSUE TITLE
Feature Request: Option to restart i3

### ISSUE THREAD

**Issue by Nebucatnetzer** [acrisci/i3ipc-python#96]
For certain use cases like moving the primary monitor it would good to have an option to restart i3.
Because it can happen that certain parts of the screen stay black and restarting i3 solves that.

**Comment by acrisci** [comment]
Can you be more specific and provide examples of what you want the library to do?

**Comment by Nebucatnetzer** [comment]
The command i3.command('restart') should work.
Currently i3ipc crashes when one executes that command.
So it probably needs a function to reconnect to i3.
A parameter like you described it here:
https://github.com/acrisci/i3ipc-python/pull/25#issuecomment-198750145

**Comment by acrisci** [comment]
How do we handle a Connection that is not connected?

**Comment by Nebucatnetzer** [comment]
Good question.
Maybe a a loop with a timeout which tries to reconnect after the restart command was executed?

**Comment by acrisci** [comment]
This commit I think will do this: fa3a813

Pass `auto_reconnect=True` to the Connection constructor to enable the feature.

Look at these tests and add to them if you're doing something different:

https://github.com/acrisci/i3ipc-python/blob/master/test/test_restart.py

https://github.com/acrisci/i3ipc-python/blob/master/test/test_shutdown_event.py

This will probably need a lot more testing before I release it.

**Comment by acrisci** [comment]
Yeah I should probably make a little docker container for testing or something.

What's your distro? I only test this on Fedora.

**Comment by acrisci** [comment]
> I noticed however that it seems to run without the auto_reconnect=True parameter.

The connection can now live in a disconnected state. It will only try to reconnect when you do the next command. Without `auto_reconnect`, it will fail with the error.

**Comment by Nebucatnetzer** [comment]
Ah okay, got it.

Aye a docker container or a Vagrant VM would be a good idea.
I'm using currently Ubuntu 18.04 and Debian Unstable.

**Comment by acrisci** [comment]
311396b makes the tests work on ubuntuy 18.04, but you need the development version of i3 for tests to pass.

**Comment by Nebucatnetzer** [comment]
Didn't have much time this week. How do you get the development version? Do you have to build it from source?

**Comment by orestisf1993** [comment]
You could just update to the newly released 4.16

**Comment by acrisci** [comment]
To test an unreleased version, clone the repository, go to the directory, and `PYTHONPATH=. /path/to/script.py`.
